<?xml version="1.0" encoding="UTF-8"?>

<!-- 

	@author: sgurin
-->

<!-- DTD -->
<!DOCTYPE Tree [

<!ELEMENT tree (section|item)*>
<!ELEMENT section (section|item)*>
	<!ATTLIST section,item name CDATA #REQUIRED>
<!ELEMENT item (section|item)*>
	<!ATTLIST item name CDATA #REQUIRED>
	
]>

<tree>
	<section name="section1.1">
		<item name="item 1.1"></item>
		<item name="item 1.2"></item>
		<section name="section1.3">
			<item name="item 1.3.1"></item>
			<item name="item 1.4.1"></item>
			<item name="item 1.5.1"></item>
		</section>
		<item name="item 1.4"></item>
	</section>

	<section name="section1.2">
		<item name="item 2.1"></item>
		<item name="item 2.2"></item>
		<item name="item 2.3"></item>
	</section>

</tree>